<?php

/**
 * @file
 * Contains social_wall.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_wall_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.social_wall':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function social_wall_theme($existing, $type, $theme, $path) {
  $themes = [];

  $themes['social_wall__block'] = [
    'variables' => [
      'elements' => [],
    ],
  ];

  $themes['social_network_instagram_block'] = [
    'variables' => [
      'elements' => [],
    ],
  ];

  $themes['social_network_twitter_block'] = [
    'variables' => [
      'elements' => [],
    ],
  ];

  $themes['social_network_facebook_block'] = [
    'variables' => [
      'elements' => [],
    ],
  ];

  return $themes;
}
